###
POST http://localhost:3000/api/ine/crear HTTP/1.1
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido_paterno": "Pérez",
  "apellido_materno": "Gómez",
  "curp": "PEPG900101HDFXXX01",
  "fecha_nacimiento": "1998-07-01",
  "sexo": "M",
  "calle": "Calle Falsa",
  "numero": "123",
  "colonia": "Centro",
  "municipio": "CDMX",
  "estado": "Ciudad de México",
  "cp": "06000",
  "clave_elector": "ABC1234567890"
}

###
GET http://localhost:3000/api/ine/consulta HTTP/1.1

###
GET http://localhost:3000/api/ine/consulta/curp/LORA920501MDFXXX09 HTTP/1.1

###
GET http://localhost:3000/api/ine/consulta/id/2 HTTP/1.1

###
DELETE http://localhost:3000/api/ine/eliminar/curp/PEPG900101HDFXXX01 HTTP/1.1




